package ee.mkv.estonian.domain;

import lombok.Getter;

public enum CompoundRule {
    COMPOUND_OF_TWO_FIRST_SINGLE_NOMINATIVE(1),
    COMPOUND_OF_TWO_FIRST_SINGLE_GENITIVE(2),
    COMPOUND_OF_TWO_FIRST_PLURAL_NOMINATIVE(3),
    COMPOUND_OF_TWO_FIRST_PLURAL_GENITIVE(4),
    COMPOUND_WORD_SEPARATED_BY_HYPHEN(5),
    COMPLEX_COMPOUND_WORD(6),
    DERIVED_FROM_NAME_WITH_SUFFIX(7),
    DERIVED_FROM_VERB_ROOT_WITH_SUFFIX(8),
    DERIVED_NAME_FROM_ADJECTIVE(9),
    DERIVED_ADJECTIVE_FROM_VERB_SUPINE_ROOT_WITH_SUFFIX(10);

    @Getter
    private final int id;

    CompoundRule(int id) {
        this.id = id;
    }
}
