spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
    hibernate.ddl-auto: none
  datasource:
    url:
    username: estonian
    password:
  liquibase:
    changelog: db/changelog/master.xml
ekilex:
  uri: https://ekilex.ee
spring.jmx.enabled: true
logging.level:
  picocli: DEBUG
